# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 888faf80784114099b7f65ca6d72eb8b0cb846fc7475c21efcf9a8753f354e63cb2c6c4f7f6d45c63a4eece6ff92f1a7a17dd31391fd3d107718205cd454022e

test:
  secret_key_base: 838a7ce03991727b14caaabd7452403b701a2a0b059a774c347586cdcf086bf449a60cdc4b1ebe180f3234b8466ffc2572a0a11c889498d21b265f59d150c00e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
